### ISSUE TITLE
📝 docs: 프로젝트 리드미 파일 작성

### ISSUE THREAD

**Issue by mihyunLee** [FRONTENDSCHOOL5/final-14-BangKKuseok#158]
## 🤷 구현할 기능
프로젝트 리드미 파일을 작성한다.

**Comment by mihyunLee** [comment]
<img src="https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/51310674/9266fabb-13e9-467d-9f66-e6b4c09bdd3d" width="120" height="120" />

**Comment by boeunLee** [comment]
- 회원가입 페이지
![ezgif com-video-to-gif](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/143730d7-99e2-4ca7-82dc-b3f6902a0247)

**Comment by boeunLee** [comment]
- 로그인 페이지
![ezgif com-video-to-gif (1)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/52e7b9cd-f4da-46c8-b568-5fca9998e8df)

**Comment by boeunLee** [comment]
- 채팅페이지
![ezgif com-video-to-gif (2)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/6420513e-ed70-4f6e-a264-04ad94708de5)

**Comment by boeunLee** [comment]
- 게시글 등록
![ezgif com-video-to-gif (3)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/8c359d9a-1de7-4888-a92f-3ac089d5c581)

**Comment by boeunLee** [comment]
-  무한스크롤
https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/5d959bbf-36da-42f3-bbb7-826cff4d940e

**Comment by boeunLee** [comment]
- 게시글 수정

https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/bce0780d-5f77-42d2-8502-ba82e7c34d6e

**Comment by boeunLee** [comment]
- 게시글 삭제
![ezgif com-video-to-gif (5)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/4b83b607-51e5-4fc9-84cf-1231999bbaf0)

**Comment by boeunLee** [comment]
- 게시물 좋아요, 댓글
![ezgif com-video-to-gif (8)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/d9ec8586-c188-44a9-9bc2-803f2f6ea152)

**Comment by boeunLee** [comment]
- 게시물 좋아요 취소, 댓글 삭제
![ezgif com-video-to-gif (9)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/fa510def-fa96-408a-bc42-5f7f0348c526)

**Comment by boeunLee** [comment]
- 게시물 신고
![ezgif com-video-to-gif (6)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/08740c8f-b989-4c7b-9b5d-2bcf8d38d91c)

**Comment by boeunLee** [comment]
- 댓글 신고
![ezgif com-video-to-gif (7)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/90bff01b-2331-4a97-b00b-bd8e8f9b3434)

**Comment by boeunLee** [comment]
- 404 페이지
![ezgif com-video-to-gif (10)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/aba5ea35-723b-4014-abc3-3a29451f84ca)

**Comment by jiwon-o** [comment]
- 홈페이지
![ezgif com-crop](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/eb59e3d1-77b7-4dcc-9abf-77b2dbd2443f)

**Comment by mihyunLee** [comment]
![image](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/51310674/ba409cda-93b0-4798-a4b5-3adb5d2e056e)

**Comment by boeunLee** [comment]
- 회원가입
![ezgif com-crop](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/ebb93b89-84c4-4232-9d4e-858ab9036adb)

- 로그인
![ezgif com-crop (1)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/8b363e41-2e2f-4cee-aa14-ee17c0925334)

**Comment by boeunLee** [comment]
- 게시물 등록
![ezgif com-crop (2)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/aff7d557-378d-46e6-8332-4d8e8350f878)

**Comment by boeunLee** [comment]
- 게시물 수정
![ezgif com-crop (3)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/a22ea70f-29a2-4954-8a24-5a035119be97)

**Comment by boeunLee** [comment]
- 게시물 등록
![ezgif com-crop (3)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/d5245238-5b62-4df9-bebf-6a3d58d23474)

**Comment by jiwon-o** [comment]
- 검색
![ezgif com-crop (4)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/bc32ad5a-e1c8-4ff4-90a0-7472fb6ada15)

**Comment by boeunLee** [comment]
- 게시물 수정
![ezgif com-video-to-gif (14)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/4aa891c4-8782-401e-a4fa-b01bf72501d5)

**Comment by boeunLee** [comment]
- 게시물 삭제
![ezgif com-crop (5)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/5dea5f8b-b211-4e1b-8cfc-8cb616d14dca)

**Comment by boeunLee** [comment]
- 좋아요, 댓글
![ezgif com-crop (8)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/68bd83cb-5a97-4e89-ae0f-fdfbb7e6ed04)

**Comment by boeunLee** [comment]
- 좋아요 취소, 댓글 삭제
![ezgif com-crop (9)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/3abbd185-26db-480f-8c7e-8b677eb8c83c)

**Comment by boeunLee** [comment]
- 게시물 신고
![ezgif com-crop (6)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/fe2dc016-8d6f-464c-b0df-f4f62a4cf9fd)

**Comment by boeunLee** [comment]
- 댓글 신고
![ezgif com-crop (7)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/5ad07feb-551f-4529-9ed6-d70a372efbdc)

**Comment by boeunLee** [comment]
- 404 페이지
![ezgif com-crop (10)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/f6a887c4-6218-4e67-9b11-cd0aa51efd0a)

**Comment by boeunLee** [comment]
- 무한스크롤
![ezgif com-video-to-gif (13)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/c30b1302-2fce-4383-bdc9-b7eda40d9c80)

**Comment by boeunLee** [comment]
- 스플래시

https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/3065a827-23aa-4690-bfa1-1b8a8578fa8e

**Comment by boeunLee** [comment]
- 스플래시
![ezgif com-video-to-gif (15)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/7376f576-9233-4872-9e86-d7ac3b0a4f71)

**Comment by jiwon-o** [comment]
- 프로필 화면, 프로필 수정, 상품 수정/삭제, 로그아웃
![ezgif com-crop (5)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/e49d04c3-a7af-49e7-b1ec-0ea0dab114b3)

**Comment by boeunLee** [comment]
![ezgif com-video-to-gif (16)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/e135b386-0668-499f-86de-87b311d85a00)

**Comment by boeunLee** [comment]
- 스플래시
![ezgif com-video-to-gif (17)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/111286497/6439f482-9e0b-4b34-bdae-09e15b553ef6)

**Comment by jiwon-o** [comment]
- 프로필 수정
![ezgif com-crop (7)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/a3ab6dbf-7404-41fb-a6e8-9e28271ce2c7)

**Comment by jiwon-o** [comment]
- 상품 수정
![ezgif com-crop (8)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/bcedf8f1-4df9-419f-aefd-fcc723cd9a93)

**Comment by jiwon-o** [comment]
- 상품 등록
![ezgif com-crop](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/4ac18b0c-2c37-4e2e-93ee-38408ec09d56)

**Comment by jiwon-o** [comment]
- 상품 삭제
![ezgif com-crop (1)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/5c4bb01c-1907-4d81-8f09-2b9e9cb2b964)

**Comment by jiwon-o** [comment]
- 팔로우/언팔로우
![ezgif com-crop (3)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/4809b56a-f84d-4893-bbf7-01ab448fcc89)

**Comment by jiwon-o** [comment]
- 로그아웃
![ezgif com-crop (4)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/a3e3f93c-ec16-4170-a750-1dde2f647ecc)

**Comment by jiwon-o** [comment]
- 스플래시
![ezgif com-crop (5)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/3a28142f-cfa4-459b-8a6a-f7dafe4676d9)

**Comment by jiwon-o** [comment]
- 회원가입-1
![ezgif com-gif-maker](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/0596e112-fba7-415a-9be6-90f50f5cfb8b)

**Comment by jiwon-o** [comment]
- 회원가입-2
![ezgif com-gif-maker (1)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/8fb03508-0828-4e84-b554-ebbe849fd09f)

**Comment by jiwon-o** [comment]
- 로그인
![ezgif com-gif-maker (3)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/dd7f1b16-9cc5-4fef-9916-67e5f5b911df)

**Comment by jiwon-o** [comment]
- 채팅
![ezgif com-gif-maker (4)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/1e2eddc2-fe82-42d0-99f7-5fc02e3527b6)

**Comment by jiwon-o** [comment]
- 게시물 등록
![ezgif com-gif-maker (5)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/b3f937b7-7367-42eb-98e2-dce07f13c9c3)

**Comment by jiwon-o** [comment]
- 게시물 삭제
![ezgif com-crop (6)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/b885415b-a204-4f33-86f9-c46218ac2646)

**Comment by jiwon-o** [comment]
- 게시물 수정
![ezgif com-gif-maker (6)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/64193469/a205ccbb-0050-4ee2-a70a-f42c01783625)

**Comment by mihyunLee** [comment]
![제목 없음](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/51310674/e3fb1f40-2bd0-49f5-a804-164e48c3878e)

**Comment by mihyunLee** [comment]
![image](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/51310674/599da020-d81b-469c-884a-cf82c9e64dfe)

**Comment by mihyunLee** [comment]
![ezgif com-video-to-gif (5)](https://github.com/FRONTENDSCHOOL5/final-14-BangKKuseok/assets/51310674/1d6e0bdd-eb47-42a2-be4c-bf6e17c22a29)
